const products = [
  {
    name: "Md Asikur Rahman",
    FathersName: "Md Atiar Rahman",
    id: "2",
    MothersName: "Mst Rupali Khatun",
    tech: "computer",
    house: "Kaligang,Jhenaidah",
    worksAt: "2020-2023",
    worksIn: "JHENAIDAH POLYTECHNIC INSTITUTE",
    join: 2020,
    studietAt: "JHPI",
    degree: "DIPLOMA IN ENGENEERING",
    Shift: "1st",
    Semester: "4th",
    birthday: "05/06/2004",
    blood: "A+(positive)",
    preAdd: "Monohorpur,Kaligang,Jhenaidah",
    parAdd: "Monohorpur,Kaligang,Jhenaidah",
    phone: "01893585782",
    email: "asikurrahaman997@gmail.com",
    roll: 532454,
    reg: 1502108345,
    session: "2020-2021",
    image: "/img/y1.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recEHmzvupvT8ZONH",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2020,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "albany sect",
    post: "Junior Instructor (Tech) Computer",
    image: "/img/y2.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "rec5NBwZ5zCD9nfF0",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "albany table",
    post: "Junior Instructor (Tech) Computer",
    image: "/img/y3.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recd1jIVIEChmiwhe",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "armchair",
    post: "Junior Instructor (Tech) Computer",
    image: "/img/y4.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recoM2MyHJGHLVi5l",
    post: "Junior Instructor (Tech) Computer",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "bar stool",
    image: "/img/y5.png",
  },
];

export default products;
