const products = [
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "2",
    post: "Junior Instructor (Tech) Computer",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "JHENAIDAH POLYTECHNIC INSTITUTE",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "Pabitra Kumar Biswas",
    image: "/img/p4.jpg",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recEHmzvupvT8ZONH",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "albany sect",
    post: "Junior Instructor (Tech) Computer",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/0be1af59cf889899b5c9abb1e4db38a4/d631ac52",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "rec5NBwZ5zCD9nfF0",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "albany table",
    post: "Junior Instructor (Tech) Computer",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/7478483f40a2f56662a87b304bd4e104/707d397f",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recd1jIVIEChmiwhe",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "armchair",
    post: "Junior Instructor (Tech) Computer",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/530c07c5ade5acd9934c8dd334458b86/cf91397f",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recoM2MyHJGHLVi5l",
    post: "Junior Instructor (Tech) Computer",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksAt: "2005-2023",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "bar stool",
    image:
      "https://dl.airtable.com/.attachmentThumbnails/a6119fabf7256049cc0e8dbcdf536c9c/b0153f66",
  },
];

export default products;
