const products = [
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "2",
    post: "Junior Instructor (Tech) Computer",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "accent chair",
    image: "/img/y5.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recEHmzvupvT8ZONH",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "albany sect",
    post: "Junior Instructor (Tech) Computer",
    image: "/img/y1.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "rec5NBwZ5zCD9nfF0",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "albany table",
    post: "Junior Instructor (Tech) Computer",
    image: "/img/y2.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recd1jIVIEChmiwhe",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "armchair",
    post: "Junior Instructor (Tech) Computer",
    image: "/img/y3.png",
  },
  {
    email: "example@gmail.com",
    phone: "018xxxxxxxxxx",
    id: "recoM2MyHJGHLVi5l",
    post: "Junior Instructor (Tech) Computer",
    tech: "computer",
    house: "Dhaka,Khulna",
    worksIn: "30year",
    join: 2006,
    studietAt: "Buet,Dhaka,Bangladesh",
    degree: "PHD,BSC,DIPLOMA IN ENGENEERING OTHERS",
    name: "bar stool",
    image: "/img/y6.png",
  },
];

export default products;
